### ISSUE TITLE
Create and Pull JSON file and show details on Contributor Work page | HacktoberFest 2023

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#101]
Hey there! This issue is tailor-made for newcomers who are just getting started with their contributions and have some development skills under their belt. We're here to welcome and support you on your journey!

## Issue :

<img width="1440" alt="Screenshot 2023-10-01 at 9 49 19 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/f98de6a8-dd04-4291-8fcb-a68cdfbe0903">

The screenshot above displays an incomplete page. As our website serves various purposes and has a significant user base, we aim to maintain a record of contributors' activities. On this page, our intention is to showcase data such as their usernames, a log of all the pull requests (PRs) they've initiated, and the objectives behind each of these PRs.

## Objectives :

1. **Create a JSON file :** Be creative in finding what kind of data would be good to show for each user. Eg. username, profile pic, pull-request dates and reason etc. If you want to get some real data you can check the <a href="https://github.com/Nayaker/AlgoListed/pulls?q=is%3Apr+is%3Aclosed" target="_blank">previous Algolisted accepted pull requests</a>. Create the JSON file named contributorsData.json in ```client > src > Components```
Note : _Create at least data for 5 users._ 

2. **Call the JSON in ContributorWork.js :** Call the JSON file in ContributorWork.js which is already present in ```client > src > Screens > ContributorWork.js``` - now be creative in the UI how you want to show the data of contributors. 
Note : _Write the CSS in the same file using Material UI_ 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to run the repo in local environment :
1. Go inside ``` client ``` in terminal
2. Run command ``` npm install ```
3. Run command ``` npm start ``` or ``` yarn start ```

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - # 101 Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by Snowfall22** [comment]
interested

**Comment by Snowfall22** [comment]
could I pls work on this?

**Comment by Nayaker** [comment]
Ok sure @Snowfall22, I am assigning the issue to you. 

**_Others who share an interest can also comment in the conversations below._**

**Comment by Snowfall22** [comment]
Thank you!

**Comment by Snowfall22** [comment]
Hi, have issues in setting up. I'm getting dependency errors on running `npm install` in the client

**Comment by Nayaker** [comment]
@Snowfall22  Send a mail on nayak.primary@gmail.com

**Comment by CollegeFellow** [comment]
@Nayaker Interested

**Comment by Nayaker** [comment]
Great @CollegeFellow I am assigning this issue to you as well. 

**_Others who share an interest can also comment in the conversations below._**

**Comment by jatingodnani** [comment]
is their any figma file??

**Comment by Nayaker** [comment]
No, there isn't a Figma file for this issue, so you have the freedom to develop whatever you like based on your creativity.

**Comment by jatingodnani** [comment]
Only PRs that are closed need to be shown in the UI

**Comment by Nayaker** [comment]
Yes!

**Comment by jatingodnani** [comment]
i am interested

**Comment by CollegeFellow** [comment]
@Nayaker I've created PR for this issue https://github.com/Nayaker/AlgoListed/pull/103
Please share your feedback.

**Comment by jatingodnani** [comment]
@CollegeFellow how to you deploy this in local beacause npm run start not working

**Comment by Nayaker** [comment]
I guess it's a issue that a lot of you are getting - wait I will update the packages soon and let you know!

**Comment by mohitsaini07** [comment]
Hi Nayaker, Is this the issue to make a video on how to run the repo locally? If, i can create that.

**Comment by jatingodnani** [comment]
![16962413916648077826824453119700](https://github.com/Nayaker/AlgoListed/assets/97869761/030e3447-166b-4539-b1dc-2f23f1b332ae)
@Nayaker i make this type of card review this and tellis this ok and suggest changes

**Comment by Nayaker** [comment]
> Hi Nayaker, Is this the issue to make a video on how to run the repo locally? If, I can create that.

I created one #104

**Comment by Nayaker** [comment]
> @Nayaker i make this type of card review this and tellis this ok and suggest changes

Great @jatingodnani, but I think the current change in the repo looks good, UI-wise! see if you can do some more creative changes to it. If yes you can create a new issue. 

<img width="1440" alt="Screenshot 2023-10-02 at 4 08 26 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/18262027-8e5d-4443-b476-57d66752b5ec">

https://github.com/Nayaker/AlgoListed/pull/103

**Comment by jatingodnani** [comment]
I thiks it look like mixing card we can give some some margin between them and add shadow to box

**Comment by jatingodnani** [comment]
But my repo is working on local.

**Comment by Nayaker** [comment]
Check @Snowfall22 @jatingodnani @mohitsaini07 #101 now the issue is resolved with the current repo changes!

**Comment by jatingodnani** [comment]
Should i need to refork the repo?

**Comment by Nayaker** [comment]
Yes I think that would be better!
