### ISSUE TITLE
Spelling Correction

### ISSUE THREAD

**Issue by shreyasanap** [Nayaker/AlgoListed#102]
-  I found a spelling mistake in the coding competitions page 
-  Incorrect: "teir" | Correct: "tier"

![image](https://github.com/Nayaker/AlgoListed/assets/121751187/1023d15b-c01a-4a2a-b00a-7da537919abe)

**Comment by Nayaker** [comment]
Resolved! Will be updated in the next push. Thanks for noticing :)
