### ISSUE TITLE
Friend Management Feature Implementation | HacktoberFest 2023

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#107]
Hey there! This issue is tailor-made for newcomers who are just getting started with their contributions and have some development skills under their belt. We're here to welcome and support you on your journey! 🚀 

We're kicking off this issue to enhance our user experience by adding some exciting friend management features. With this update, users will be able to effortlessly see their friends' performance in a contest. 

<img width="1440" alt="Screenshot 2023-10-03 at 2 03 35 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/33cce523-6a48-47e7-a42b-22a47ff1115b">

## Tasks : 
0. The file you need to work upon is ```client > src > Screen > ContestAnalysis.js```
1. Create a form with fields for the friend's username and picture URL.
2. Trigger this form when the user clicks the "add friend" button.
3. Store the entered data in local storage.
4. Utilize the country-rank-data retrieved to determine the friends's rank.
5. Since the API does not provide the number of problems solved, use a dummy value for it or just write N/A.
6. Make the cross button functional to allow users to remove a friend from local storage.

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - # 107 Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by jatingodnani** [comment]
interested

**Comment by Nayaker** [comment]
Great @jatingodnani let me assign this issue to you.

**Comment by jatingodnani** [comment]
i request you to pls assign one issue to one person only.

**Comment by Nayaker** [comment]
Okay sure, it would be assigned to you only for the next 24 hours :) Happy coding 🚀

**Comment by Nayaker** [comment]
@jatingodnani If you are having any issues with running the repo locally, then ask @Mohit030802 (Repo Maintainer) he will solve it. _You can also ask him to get on a gmeet to solve it._

**Comment by jatingodnani** [comment]
solved !
i have a ques ,the table which is showing in above screenshot is not showing in actual ui
![Screenshot 2023-10-03 171827](https://github.com/Nayaker/AlgoListed/assets/97869761/88a88025-8fe6-42cf-a9eb-7d3bfb934ab0)

**Comment by Nayaker** [comment]
Click on the search btn, then you go inside another page ```http://localhost:4000/contest-analysis/weekly-contest-361```

**Comment by jatingodnani** [comment]
is their any gc for doubt

**Comment by Nayaker** [comment]
Nope sorry :( since it is a small repo I have not created one yet!
You can ask your doubts directly on this issue, so others can also have a track of the progress :)

**Comment by jatingodnani** [comment]
if we take name(leetcodename) and url from form how we fetch the ranking ?is there any api

**Comment by Nayaker** [comment]
Yes! there is an API which is getting called ```https://nayak-leetcode-api.vercel.app/?weekly_contest=${contestName}``` which has all the data. 

_Check your mail_

**Comment by jatingodnani** [comment]
should i make modal type form if we click form will be open

**Comment by Nayaker** [comment]
Yes you can do that, a small modal would be good

**Comment by jatingodnani** [comment]
why you are not using tailwind

**Comment by Nayaker** [comment]
The most honest answer is - The project began a year and a half ago, and during that period, I didn't feel very confident in my knowledge of tailwind CSS. Maybe in v3.0+ I will start implementing that.

**Comment by jatingodnani** [comment]
can i make new folder which contain components like modal,etc

**Comment by jatingodnani** [comment]
hlo,i have one doubt in this api [https://nayak-leetcode-api.vercel.app/?weekly_contest=${contestName}] is contest name is like ex:361 is this a number,if yes then i need to search the name for specific user??

**Comment by jatingodnani** [comment]
Hlo,should i take country name in form to filter easily or should i filter from all countries data?

**Comment by Nayaker** [comment]
How will it ease the search? 

I would suggest not taking the country name because the user might not know the country of his friend, and even if he knows his friend can change his country again and again and we wouldn't have a track. 

So I think just search in the list and find the username of the friend corresponding to the country name "All Countries" and give that global rank. 

_If I miss-understood your query then do let me know_

**Comment by jatingodnani** [comment]
Ok

**Comment by jatingodnani** [comment]
@Nayaker my issue is almost complete,i will raise the pr in evening

**Comment by Nayaker** [comment]
Amazing man 🔥

**Comment by jatingodnani** [comment]
i am facing difficulty in raising pr

**Comment by Nayaker** [comment]
@jatingodnani any update? I think you texted something, I have missed it :(

**Comment by jatingodnani** [comment]
@Nayaker review my pr

**Comment by Nayaker** [comment]
<img width="929" alt="Screenshot 2023-10-06 at 2 13 11 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/c8ad928a-981e-4b27-bcdd-0383a54ccd7b">

@jatingodnani in your PR #112 : I think, you have saved the user's friend's usernames and their ranks on the user's computer right? Well, that caused a big problem because it kept the same ranks for different contests. So, my idea is to only save your friend's usernames, and when you want to see their ranks for a different contest, we can search for them then.

**Comment by jatingodnani** [comment]
Yes,this is a prblm.
@Nayaker add some more issue
