### ISSUE TITLE
Dark Mode Feature in Coding Sheets Page | HacktoberFest 2023

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#109]
Hey there! This issue is tailor-made for newcomers who are just getting started with their contributions and have some development skills under their belt. We're here to welcome and support you on your journey! 🚀 

Since we didn't plan from the start that we would go for the dark mode, it's hard now to get the whole project in dark mode. Hence we are going one by one, one page after another. This would be the first!

<img width="1440" alt="Screenshot 2023-10-04 at 7 46 50 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/f0ed8ac4-5683-4d37-a85d-e7538c1753d9">

## Tasks : 
0. Your task involves working on the file located at client > src > Screen > CodingSheets.js.
1. Generate a global CSS file named "dark mode colors."
2. In the above global CSS file, establish color variables that can be adjusted later, such as --dark-color-1: rgba(0,0,0,.5).
3. Create a button, as described, within the "cc-header" file.
4. Implement a function where toggling the button results in a switch to dark mode on the page.
5. Additionally, save this preference in local storage so that if a user previously used dark mode, it will be retained for their next visit.

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - # 109 Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by soumyadeeproychowdhury** [comment]
Hi! I would love to work on this issue!

**Comment by Nayaker** [comment]
Amazing to see your interest :)
Sure, I am assigning this task to you @soumyadeeproychowdhury!  
Happy coding 🚀

**Comment by soumyadeeproychowdhury** [comment]
Thank you will be giving time to time updates! @Nayaker

**Comment by Nayaker** [comment]
@soumyadeeproychowdhury any update buddy?!

**Comment by riyanrathore26** [comment]
Hi @Nayaker 
please assigne me this issue
I would love to work on this issue!

**Comment by Nayaker** [comment]
Sure @riyanrathore26, but I want you to know a few changes that are required. Are you up for a google meet right now?

**Comment by riyanrathore26** [comment]
yes i am ready for google meet
please share link

**Comment by Nayaker** [comment]
Can you share me your email/discord/WhatsApp

**Comment by riyanrathore26** [comment]
WhatsApp. +916378948871

**Comment by thakurthegr8** [comment]
is this issue still available? @Nayaker

**Comment by Nayaker** [comment]
@thakurthegr8, we appreciate your interest, but we regret to inform you that the dark mode features are being discontinued.

**Comment by thakurthegr8** [comment]
Oh i tried to add some code it worked app wide @Nayaker 
https://github.com/Nayaker/AlgoListed/assets/68949544/bdf1e2bf-344c-4c02-b7ac-84dbc69b2cd9

**Comment by Nayaker** [comment]
Amazing @thakurthegr8, I have talked with your friend Anuj - We will do a google meet tomorrow!

**Comment by thakurthegr8** [comment]
Sure @Nayaker
