### ISSUE TITLE
Dark Mode Feature in Resources Page | HacktoberFest 2023

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#110]
Hey there! This issue is tailor-made for newcomers who are just getting started with their contributions and have some development skills under their belt. We're here to welcome and support you on your journey! 🚀 

Since we didn't plan from the start that we would go for the dark mode, it's hard now to get the whole project in dark mode. Hence we are going one by one, one page after another. 

<img width="1440" alt="Screenshot 2023-10-04 at 8 03 22 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/4350595d-0e5b-453d-86e5-118a37655e4b">

## Tasks : 
0. Your task involves working on the file located at client > src > Screen > Resources.js.
1. Generate a global CSS file named "dark_mode_colors_resources"
2. In the above global CSS file, establish color variables that can be adjusted later, such as --dark-color-1: rgba(0,0,0,.5).
3. Create a button, as described, within the "cc-header" file.
4. Implement a function where toggling the button results in a switch to dark mode on the page.
5. Additionally, save this preference in local storage so that if a user previously used dark mode, it will be retained for their next visit.

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - # 110 Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by shibs-01** [comment]
please assign me this task

**Comment by Nayaker** [comment]
Sure, I am assigning this task to you @shibs-01!

**Comment by SurajPrakash24** [comment]
Heyy I would also like to work on this task. Can you please assign

**Comment by Nayaker** [comment]
@SurajPrakash24 Great! Please share this assignment with @shibs-01. 

_You both can collaborate on the problem, or do it independently and if both of your efforts yield satisfactory results, both of your pull requests will be accepted._

**Comment by enayush** [comment]
@Nayaker Please help me out
I'm unable to run this website locally.
I had already referred to https://github.com/Nayaker/AlgoListed/issues/104 
But it's not working.

**Comment by Nayaker** [comment]
Give your email address here. 

_I will delete the you email from the comment section later on_

**Comment by Nayaker** [comment]
@SurajPrakash24 @shibs-01 is it working for you guys?

**Comment by enayush** [comment]
@Nayaker 
en.ayushshr@gmail.com

**Comment by Nayaker** [comment]
Check mail @enayush

**Comment by SurajPrakash24** [comment]
> @SurajPrakash24 @shibs-01 is it working for you guys?

Yes it's working

**Comment by riyanrathore26** [comment]
can i work on it?

**Comment by Nayaker** [comment]
@riyanrathore26 Amazing! I am assigning this issue to you as well. 

_If another person submits a pull request for this issue before you, don't fret; if your pull request is valid, it will still be considered and accepted!_

**Comment by Nayaker** [comment]
@SurajPrakash24 @shibs-01 any update?

**Comment by nivedt** [comment]
Can I work on this issue??

**Comment by Nayaker** [comment]
Nice @nivedt! I am assigning this issue to you as well :) 

_If another person submits a pull request for this issue before you, don't fret; if your pull request is valid, it will still be considered and accepted!_

**Comment by SurajPrakash24** [comment]
Hey @Nayaker! I have created a PR, Please review and merge as hacktoberfest-accepted

**Comment by Nayaker** [comment]
Sure, I will accept the PR it is good. However, there is a slight bit of changes that you can make, and generate a second PR as well!

**Comment by Nayaker** [comment]
<img width="1440" alt="Screenshot 2023-10-06 at 8 06 31 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/4dcb8fba-af3e-4e8c-8152-42d1e6e86f3d">

@SurajPrakash24 can you please try to give a PR similar to this!

**Comment by Nayaker** [comment]
@SurajPrakash24 But I think the toggle button looks amazing so I would suggest you keep that, and remove the button which we have here. 

But try to match the colors as the above.

**Comment by riyanrathore26** [comment]
HI @Nayaker 
i am beginner and facing some problem while setup localy 
can you explain how i can run this repo localy

**Comment by Nayaker** [comment]
@riyanrathore26 Check https://github.com/Nayaker/AlgoListed/issues/104

**Comment by riyanrathore26** [comment]
Hi @Mohit030802 
I have some question related to setup in local machine 
1. can you send list of usefull library's 
2. and I want to create new database in mongodb
3. and how i can change port in localhost etc

**Comment by Mohit030802** [comment]
Hi @riyanrathore26,

1. Use ```npm i``` or ```npm i --force``` to install all the required dependencies.
2. To change PORT in your localhost go to ```package.json``` and you will find the ```PORT=4000``` mentioned in the start script just change the port number as per your requirement.

**Comment by riyanrathore26** [comment]
@Mohit030802 Now facing some error in database connectivity
like 
(node:9596) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at Connection.openUri (D:\git demo\algolisted\backend\node_modules\mongoose\lib\connection.js:695:11)   
    at D:\git demo\algolisted\backend\node_modules\mongoose\lib\index.js:409:10
    at new Promise (<anonymous>)
    at promiseOrCallback (D:\git demo\algolisted\backend\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (D:\git demo\algolisted\backend\node_modules\mongoose\lib\index.js:1262:10)
    at Mongoose.connect (D:\git demo\algolisted\backend\node_modules\mongoose\lib\index.js:408:20)
    at Server.<anonymous> (D:\git demo\algolisted\backend\index.js:44:12)
    at Object.onceWrapper (node:events:628:28)
    at Server.emit (node:events:514:28) etc

**Comment by Nayaker** [comment]
@riyanrathore26 you don't have to run the backend, just run the frontend part.

**Comment by riyanrathore26** [comment]
@Nayaker  sorry to say that i am tried but i am unable to run only fron end or full project 
can you explain in more breif

**Comment by Mohit030802** [comment]
Hi @riyanrathore26,

To run the front end of the project follow these steps.
1. Go to the client folder in the terminal ``` cd client```
2. Now to install the required dependencies use ```npm i --force```.
3. And once the required dependencies are installed just use ```npm start``` to run the repo on your local machine.

 and as you are working in Dark mode there is no need to use the backend.
 
I have added a detailed video for the following in #104 you can refer to it. If you still face any issues we will organize a G-meet also for you.

**Comment by Mohit030802** [comment]
Hi, @NilanjanPramanik, we really appreciate your interest, but this issue has already been resolved. We are planning to create many more issues soon, and we will tag you. 

Please star this repo, so you will be informed if there are any issues that you can help solve. We would love to see your contributions.
