### ISSUE TITLE
Global CSS file : Allcss is hampering other files | HacktoberFest 2023

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#114]
I've noticed that the Allcss file is well-made, but it may pose some issues because, throughout the project, we have refrained from using global CSS variables. The global CSS file is only needed for the contest analysis page, so it would be more appropriate to confine the CSS changes to that specific file instead of making them global.

Issue : example it has issues in ```client > src > Screens > showdownServer.js```
<img width="1440" alt="Screenshot 2023-10-04 at 8 02 01 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/b7f7b937-6df1-4197-8992-142139d2e1d5">

![WhatsApp Image 2023-10-04 at 8 13 09 PM](https://github.com/Nayaker/AlgoListed/assets/93304796/c46b5e9e-ec2e-4317-9ec3-015c353c9192)

## Task : 
1. make ```client > src > Allcss``` local to ```client > src > Screens > contestAnalysis.js```

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - # 110 Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by jatingodnani** [comment]
Not understand properly

**Comment by Arun-Raghav-S** [comment]
Hey, could you assign this to me? I am interested to work on this

**Comment by Nayaker** [comment]
> Not understand properly

In both the showdownServer.js styled component and the AllCSS model.css, there is a 'btn' class div. However, the desired property is being unintentionally modified in showdownServer.js.

**Comment by Nayaker** [comment]
> Hey, could you assign this to me? I am interested to work on this

@Arun-Raghav-S Amazing! I am assigning this issue to you, try to resolve it! It would be better if you could discuss what you are planning to do.

**Comment by jatingodnani** [comment]
So i can change class.i would resolve issue

**Comment by Nayaker** [comment]
Yeah that would be the easiest approach!

**Comment by Arun-Raghav-S** [comment]
Isn't it better to change the ```className``` of the modal jsx file to ```modal-button``` and the body to ```modal-body``` ? Since modal is a reusable component and it may create further issues in the future

**Comment by Nayaker** [comment]
> Isn't it better to change the `className` of the modal jsx file to `modal-button` and the body to `modal-body` ? Since modal is a reusable component and it may create further issues in the future

Yes, I agree with your observation. I believe renaming the className of the modal JSX file to 'modal-button' and the body to 'modal-body' would be a wise choice. Given that the modal is a reusable component.

**Comment by Arun-Raghav-S** [comment]
@Nayaker  Please review my PR #116

**Comment by Nayaker** [comment]
@Arun-Raghav-S Check the review on PR!

**Comment by jatingodnani** [comment]
@Nayaker i resolve the issue

**Comment by Nayaker** [comment]
You already resolved?

**Comment by jatingodnani** [comment]
Yup

**Comment by Nayaker** [comment]
Generate PR!

**Comment by jatingodnani** [comment]
@Nayaker check pr
