### ISSUE TITLE
Contest Archive Data | HacktoberFest 2023

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#115]
![image](https://github.com/Nayaker/AlgoListed/assets/93304796/57461592-72c8-4f94-8df0-b514df3a03db)

## Tasks : 
1. Create a script to retrieve information from the LeetCode website regarding questions hosted on a specific website.
2. Organize the scraped data by either creating a new folder for storage or saving it in the localDB folder.

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - # 115 Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by sailikpandey22** [comment]
I am interested
