### ISSUE TITLE
Contest page | Friends rank staying same for different contests

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#119]
<img width="929" alt="Screenshot 2023-10-06 at 2 13 11 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/c8ad928a-981e-4b27-bcdd-0383a54ccd7b">

@jatingodnani in your PR #112 : I think, you have saved the user's friend's usernames and their ranks on the user's computer right? Well, that caused a big problem because it kept the same ranks for different contests. So, my idea is to only save your friend's usernames, and when you want to see their ranks for a different contest, we can search for them then.

_Originally posted by @Nayaker in https://github.com/Nayaker/AlgoListed/issues/107#issuecomment-1749620959_

**Comment by jatingodnani** [comment]
Ok,i will correct this code

**Comment by jatingodnani** [comment]
@Nayaker i think sight is still hanging

**Comment by Nayaker** [comment]
> @Nayaker i think page is still hanging

It's actually functioning well on my side, and I've also tested it on my friend's laptop with minimal to no slowdowns. However, if there are any concerns, I'm willing to investigate it further.

**Comment by Nayaker** [comment]
> Ok, should i do ?

@jatingodnani yes please

**Comment by jatingodnani** [comment]
any more issue??

**Comment by Nayaker** [comment]
Currently, aside from the mentioned issue, there are no additional concerns.

**Comment by Nayaker** [comment]
![image](https://github.com/Nayaker/AlgoListed/assets/93304796/4111dc8d-4d4c-4087-b79e-4f88be55f55a)

**Comment by jatingodnani** [comment]
@Nayaker issue resolved

**Comment by Nayaker** [comment]
> @Nayaker issue resolved

Amazing @jatingodnani generate an PR

**Comment by Nayaker** [comment]
Resolved with - #123 and #125, great stuff @jatingodnani
