### ISSUE TITLE
Redis Caching for Performance Boosting in Contest Analysis Page

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#126]
<img width="685" alt="Screenshot 2023-10-06 at 11 45 51 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/20782d8a-522f-4c5b-a8f5-e4a925774409">

## Task : 
1. Install Redis and Configure: Set up Redis on the server and configure it with the necessary settings (port, host, password).
2. Integrate Redis: Incorporate Redis into your Flask API by importing the library and establishing a connection.
3. Cache API Responses: Store API responses in Redis using contest-id as keys and response data as values.
4. Implement Cache Expiry: Set expiration times for Redis keys to keep data fresh, and update the cache when data expires.
5. Optimize API Endpoints: Modify API endpoints to check Redis first for data, and if not found or expired, retrieve and cache the latest data from the API.

Flask API : https://nayak-leetcode-api.vercel.app/?weekly_contest=weekly-contest-361 

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - #126 Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by priyam-03** [comment]
I am interested. I want to work on this issue.

**Comment by Nayaker** [comment]
Great @priyam-03, I am assigning this issue to you. Good luck!

**Comment by jatingodnani** [comment]
@Nayaker if you are using redis then you need setup docker

**Comment by Nayaker** [comment]
> @Nayaker if you are using redis then you need setup docker

is it necessary? @jatingodnani @priyam-03

**Comment by jatingodnani** [comment]
Yes,it is
![Screenshot_20231007_005258_Chrome](https://github.com/Nayaker/AlgoListed/assets/97869761/b005d4e1-289c-4450-aa75-abba81db721f)

**Comment by Nayaker** [comment]
I will look into this thanks for the info @jatingodnani
