### ISSUE TITLE
Want to work with us ? (Not an Issue)

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#13]
Write your skills in the comments, can be anything from React JS to if you are good at note-making. We will love to work with you.

**Comment by jinitsuga** [comment]
Hi - I'd like to tackle an issue or two! Decent Reactjs experience, styled-components, firebase, been diving into Nodejs recently.

**Comment by Nayaker** [comment]
Great @jinitsuga, nice to know which technologies you use.

**Comment by tylerarend** [comment]
Hello, I would love to contribute to this project if there is space for me in the group. I have experience in HTML, CSS, and JavaScript. I also have some experience (but not as much) with Node.js, EJS, Express.js, MongoDB, and OOP.
