### ISSUE TITLE
Coding Sheets | Create a multi-select topic select button, for DSA tags based filter 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#132]
Design a versatile topic selection button that allows users to choose multiple options, enabling them to filter topics with dsa- tags effortlessly. This feature enhances the user experience by providing a convenient way to refine their search within the topics related to data structure and algorithms (DSA).

<img width="410" alt="Screenshot 2023-10-09 at 8 33 05 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/3dd4a41d-a7e3-4b2f-af12-72fe1cf3c03b">

@jatingodnani

**Comment by jatingodnani** [comment]
Interested

**Comment by jatingodnani** [comment]
@Nayaker  my query is anyone choose array and hash in tags so i need to show this question and if anyone choose any one of them then i need to show same ques also?
![Screenshot 2023-10-11 002954](https://github.com/Nayaker/AlgoListed/assets/97869761/f8255a0f-ca58-4172-a7a3-7e6a9047b8c2)

**Comment by Nayaker** [comment]
> @Nayaker my query is anyone choose array and hash in tags so i need to show this question and if anyone choose any one of them then i need to show same ques also? ![Screenshot 2023-10-11 002954](https://user-images.githubusercontent.com/97869761/274035934-f8255a0f-ca58-4172-a7a3-7e6a9047b8c2.png)

Certainly, @jatingodnani, this is similar to a bitwise AND operation. When the 'array' option is selected, only problems containing both 'array' and potentially other tags are displayed, essentially making 'array' a requirement. Now, when both 'array' and 'hashtable' are selected, problems featuring 'array' and 'hashtable,' along with possibly other tags, are shown, with the caveat that problems solely tagged as 'array' without 'hashtable' are excluded.

**Comment by Nayaker** [comment]
@jatingodnani 
The above commit has a couple of issues that necessitate additional changes:

1. The feature functions flawlessly when a single filter is selected but encounters problems with multiple selections.
2. It is recommended to eliminate the 'show less' and 'show more' buttons due to their limited significance and instead set the box height to 500px and add an 'overflow: scroll' property.

I've also made some CSS adjustments to align the changes with my current UI. Additionally, could you please ensure that when creating a PR, you only commit the specific files you intend to submit, rather than the entire set of changes? :)

**Comment by jatingodnani** [comment]
> > @Nayaker my query is anyone choose array and hash in tags so i need to show this question and if anyone choose any one of them then i need to show same ques also? ![Screenshot 2023-10-11 002954](https://user-images.githubusercontent.com/97869761/274035934-f8255a0f-ca58-4172-a7a3-7e6a9047b8c2.png)
> 
> Certainly, @jatingodnani, this is similar to a bitwise AND operation. When the 'array' option is selected, only problems containing both 'array' and potentially other tags are displayed, essentially making 'array' a requirement. Now, when both 'array' and 'hashtable' are selected, problems featuring 'array' and 'hashtable,' along with possibly other tags, are shown, with the caveat that problems solely tagged as 'array' without 'hashtable' are excluded.

So you are saying if anyone choose array it should only where it contain only one tag array

**Comment by Nayaker** [comment]
No bro! Wait for some time I will explain @jatingodnani

**Comment by jatingodnani** [comment]
Ok

**Comment by Nayaker** [comment]
@jatingodnani are you online - reply to this comment in 5 mins then i can send you a gmeet link

**Comment by jatingodnani** [comment]
After 1pm

**Comment by Nayaker** [comment]
Around 1pm I will send a link to you on your email to join!

**Comment by jatingodnani** [comment]
@Nayaker close this issue
