### ISSUE TITLE
Update ContestArchive.js to Fetch Data from LcContests.json

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#135]
## Task Description
You need to update the `client > src > Screens > ContestArchive.js` file to fetch and display data from `client > src > DummyDB > LcContests.json`.

<img width="1430" alt="Screenshot 2023-10-12 at 12 27 28 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/c3dfcebf-9f54-4a4c-920c-0274a04b3e1d">
<img width="1440" alt="Screenshot 2023-10-12 at 12 32 00 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/8c99b04a-b375-498f-bc01-eed0900d6b8f">

## Steps to Complete the Task 
1. Open the `ContestArchive.js` file in your project which is present at location - `client > src > Screens > ContestArchive.js`.
2. Locate the part of the code where random data is currently being used.
3. Replace the code that uses dummy data with code to fetch data from `LcContests.json` which is present at location `client > src > DummyDB > LcContests.json`
4. Ensure that the data is displayed correctly in the UI.
5. Test the changes to make sure they work as expected.

## Additional Information
You can access the `ContestArchive.js` file in your project at `http://localhost:3000/contests-archive` when running your project locally.

## Expected Output
The `ContestArchive.js` file should no longer use dummy data and should display data from `LcContests.json` when accessed at `http://localhost:3000/contests-archive`.

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - #{issue_number} Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by Yogeshp0012** [comment]
Can you please assign this to me?

**Comment by Nayaker** [comment]
Amazing @Yogeshp0012 Issue #135 is now yours. Have fun working on it and don't forget to star the project! ⭐

_If you find any difficulties in starting the project locally then send the screenshots of the error on #104 @Mohit030802(maintainer) will help you resolve it_

Happy coding! 🚀
