### ISSUE TITLE
Add Contest Type Dropdown and 'Last X Contests' Slider to ContestArchive.js

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#138]
## Issue Task 
Modifications are required in the "ContestArchive.js" file, located in the `client > src > Screens > ContestArchive.js`. The provided image highlights two specific areas for improvement.

<img width="1440" alt="Screenshot 2023-10-13 at 6 09 10 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/6d66f0be-967c-4a5f-aa95-39e0f526814d">

### Contest Type Dropdown
In the "ContestArchive.js" file, we need to add a dropdown to allow users to select between different contest types. There are two contest types: "weekly" and "biweekly." We want to provide three options in the dropdown:

- Both Contest Types
- Weekly Contests only
- Biweekly Contests only

<img width="689" alt="Screenshot 2023-10-13 at 6 20 07 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/60dfce20-d335-4dac-bab9-b1b721ee92a2">

The contest data displayed on the page should change according to the option selected by the user. 

### "Last X Contests" Slider
We also want to add a slider for selecting the number of contests to display. By default, the slider should be set to 15, and a button should display "Last 15 Contests." When the button is clicked, a full-width slider should appear, starting with 5. The slider should increment by 5 at each step until it reaches "All."
Or you can also create a non-linear slider like : 5 - 10 - 15 - 20 - 25 - 50 - 75 - 100. Check below : 

<img width="1440" alt="Screenshot 2023-10-13 at 6 22 30 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/bf625cd7-ef6c-4675-90ad-b12b678435b6">

## Additional Information
You can access the `ContestArchive.js` file in your project at `http://localhost:3000/contests-archive` when running your project locally.

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - #{issue_number} Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by maazshakeel** [comment]
Can I get assigned on this issue?

**Comment by Nayaker** [comment]
Amazing @maazshakeel, I am assigning this task to you.

**Comment by maazshakeel** [comment]
Thanks and starred the repo! 😉

(Working on this issue....)

**Comment by maazshakeel** [comment]
@Nayaker I wont be working on this issue. (I've got some system problem here, So it may take some time)

Hope you understand. (But Looking forward to work on other issues in this repo, lets go)

**Comment by Nayaker** [comment]
No issues @maazshakeel, thanks for your interest :)

**Comment by Nayaker** [comment]
@JordanAdair can you please solve this issue?

**Comment by GouravDutta-01** [comment]
I am interested to work on this issue. Please assign this to me

**Comment by Nayaker** [comment]
Sure @GouravDutta-01

**Comment by Rhythm1710** [comment]
I also want to work on this issue. Can i help in this?

**Comment by Nayaker** [comment]
Sure @Rhythm1710

**Comment by Nayaker** [comment]
@GouravDutta-01 and @Rhythm1710 : _both of your all's PRs will be accepted_

**Comment by Nayaker** [comment]
Issue resolved!
