### ISSUE TITLE
Track Solved Problems and Save User Progress in Local Storage

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#144]
## Issue Task 
Modifications are required in the "ContestArchive.js" file, located in the `client > src > Screens > ContestArchive.js`. The provided image highlights two specific areas for improvement.

<img width="1440" alt="Screenshot 2023-10-14 at 10 23 20 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/52a9b023-bd55-4963-8aac-8a7eafdc3593">

### 1. Save and Show the Solved Problems
When a user clicks on a problem's checkbox, it means they have solved the problem. We can mark it as solved by applying a CSS class called "solved-problem" that changes the background color, just like in the example code. Additionally, we should save this information locally on the user's device so that the next time they visit, they can see their previously solved problems. This way, users can track their progress and easily identify the problems they've already solved.

### 2. Save the HideTags Usestate value 
Save the information usestate value changed by hide-tags button in localstorage.

## Additional Information
You can access the `ContestArchive.js` file in your project at `http://localhost:3000/contests-archive` when running your project locally.

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - #{issue_number} Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by mit-anuj** [comment]
Hi @Nayaker please assign me this issue . I will try to solve this issue as soon as possible

**Comment by Nayaker** [comment]
Amazing @mit-anuj, I am assigning this issue to you. 
Really happy to see someone from leetcode for a feature that is being built for leetcode :) 

_Please consider giving our project a star ⭐️ as it helps enhance the project's credibility._

**Comment by Nayaker** [comment]
@mit-anuj did you start working on this?

**Comment by mit-anuj** [comment]
I was understanding your code and there were some errors so first I resolved that.
But I will start working on the issue today and I will do my best to complete it by tommorow

**Comment by Nayaker** [comment]
Ok cool! 👍
Is the application running now? Or, do you need any help? @mit-anuj

**Comment by mit-anuj** [comment]
now it is running fine.
I just wanted to know one thing that right now you have hard coded 4 div's in the dummy contest 1 div ,so are you keep it that way or you are going to add them dynamically in future? or it just that you will add data in those four div dynamically but you will keep those 4 div's hard coded?

**Comment by Nayaker** [comment]
We can have a Google Meet to explain this @mit-anuj 
I am waiting for the next 10 minutes on the meet (https://meet.google.com/ccg-ueoo-kqy)

**Comment by Nayaker** [comment]
Can you share your WhatsApp number @mit-anuj?

**Comment by mit-anuj** [comment]
yaa sure 8077621730

**Comment by jatingodnani** [comment]
@Nayaker is this issue completed??
