### ISSUE TITLE
A feature to add internship and job opportunities

### ISSUE THREAD

**Issue by lakshay451** [Nayaker/AlgoListed#152]
The click here link at Jobs and Internship section redirects back to the home page.
![image](https://github.com/Nayaker/AlgoListed/assets/89472581/0c288527-ecda-4d75-9b93-ec7c6a9406f3)

We can add a features where authorized user can add an opportunity which will be visible to all. We can keep it simple like just the heading and the application link or can define a proper format for that.

I would like to work on this issue @Nayaker

**Comment by Nayaker** [comment]
<img width="1440" alt="Screenshot 2023-10-16 at 11 10 24 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/fb5ec194-e93a-4b6d-92cc-54a5bda847b2">

There has been an update on this, check the above image. @lakshay451 

_You can suggest if you have any inputs_
