### ISSUE TITLE
Add "Continue with Google" button functionality  | Custom Coding Sheets

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#153]
Develop the "Proceed with Google" feature and establish a backend structure depicted in the image for users. Display the "Your Sheets" and "Sheets you've Starred" sections in the lower part after login, and hide them otherwise.

<img width="1440" alt="Screenshot 2023-10-17 at 12 23 54 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/dea92ee7-b010-4db3-b815-7f04507fb618">

<img width="950" alt="Screenshot 2023-10-17 at 12 28 33 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/f3651bc3-f702-40fe-9830-bc879473fb68">

**Comment by mit-anuj** [comment]
So basically in this you want that if a person is logged in then show those two section and if not then hide them?

**Comment by mit-anuj** [comment]
assign it to me

**Comment by Nayaker** [comment]
> So basically in this you want that if a person is logged in then show those two section and if not then hide them?

Yes

**Comment by Nayaker** [comment]
No, but it's assigned already to @mit-anuj
