### ISSUE TITLE
Make the colors in chart better | Coding Sheets 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#162]
<img width="1016" alt="Screenshot 2023-10-17 at 8 49 32 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/5c6be2e1-3450-4171-a1ce-5f73b97f8505">

Task : The colors in the graph look very un-coordinated, try to make it better visually. 
For example see the below, we want it to go from dark to light slowly. 

<img width="200" alt="Screenshot 2023-10-17 at 8 51 08 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/0a8019bb-4efd-4929-8f2f-3491164d2624">

**Comment by lakshay451** [comment]
Okay, will start looking into it.

**Comment by Nayaker** [comment]
Great @lakshay451, I am assigning this task to you.

**Comment by lakshay451** [comment]
I have tried this-
![image](https://github.com/Nayaker/AlgoListed/assets/89472581/4acc5d04-f181-466f-83d6-8a6f3ee304dd)

**Comment by lakshay451** [comment]
Is it fine?
![image](https://github.com/Nayaker/AlgoListed/assets/89472581/2001707c-1ac4-4b38-9c34-973e2967bb80)
