### ISSUE TITLE
Create a creative 404 not found page 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#164]
In `app.js` inside the client folder you can see `<Route path="*" element={<PageNotExist/>} />`, you need to update PageNotExist.js. 

Make something like this : https://techcrunch.com/wp-content/uploads/2016/05/bitly.gif?w=700&crop=1

**Comment by Shuhua-L** [comment]
Hi, I would like to work on this issue, can you assign it to me?

**Comment by Nayaker** [comment]
Amazing @Shuhua-L, I am assigning the issue to you. Happy coding 🚀

**Comment by Shuhua-L** [comment]
Hey @Nayaker, I've put together a sample page to illustrate the design. Please let me know what you think. If it's to your liking, I'll go ahead and integrate it into the PageNotFound.js file.
![404-page-plan](https://github.com/Nayaker/AlgoListed/assets/83729360/e111827e-d022-427b-9b83-acce700a8bee)

**Comment by Nayaker** [comment]
Amazing looks good, I think the text can be made a bit bigger. And write - "404 Page Not Found"

**Comment by Nayaker** [comment]
Any update on this @Shuhua-L ?

**Comment by Shuhua-L** [comment]
@Nayaker I'm working on converting the sample page I built with HTML & CSS to styled components, but I couldn't get the app to run on my computer. I've checked out issue #104 and used `npm i --force` to install dependencies, but I'm still getting some errors.

![ErrorMessages](https://github.com/Nayaker/AlgoListed/assets/83729360/be2ca801-637a-43a1-971d-51128b079a2f)

**Comment by Nayaker** [comment]
It appears to be a minor issue that can be resolved. If you'd like, we can set up a Google Meet or Skype call to discuss it further. Kindly send me an email at [nayak.primary@gmail.com](mailto:nayak.primary@gmail.com) with your preferred meeting time in UTC, and we can coordinate a suitable time for our discussion. 

Alternatively, you can also post your question with the hashtag #104 and tag @Mohit030802, and he will assist in resolving it.
