### ISSUE TITLE
Create Charts for Contest Archive Page | Chart JS React 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#165]
On this page, we need to add the visualization feature. 

<img width="1440" alt="Screenshot 2023-10-18 at 4 57 50 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/15c044af-c0d0-4eda-8589-862b66391691">

## Issue 
We want to display all the tags from the filtered contest data. The bar graph is grouped by the type of problems (A, B, C, D) in which the questions were asked. If the user wants, they can also hide specific problem types by unchecking the corresponding checkbox. You can refer to the Figma image for a clearer illustration of this task : 
<img width="634" alt="Screenshot 2023-10-18 at 4 54 39 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/a425b5fe-bd7f-43ce-a075-0efb37dc781a">

## What is filtered data of contests? 
<img width="1075" alt="Screenshot 2023-10-18 at 4 58 54 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/c54590a2-afbe-480d-8c9a-06e9c99b5668">
Because the user can adjust the data and wants to see the chart for the filtered contests, please use the following code to create the chart: ```const [filteredContestData, setFilteredContestData] = useState(contestsData)```

## Additional Information
- You this link for stacked bar graphs in chart js : https://www.chartjs.org/docs/latest/samples/bar/stacked.html 
- You can access the `ContestArchive.js` file in your project at `http://localhost:3000/contests-archive` when running your project locally.

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - #{issue_number} Issue Resolved | {something you want to mention}
3. Write a good PR comment with a screen-shot of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by Nayaker** [comment]
You this link for stacked bar graphs in chart js : https://www.chartjs.org/docs/latest/samples/bar/stacked.html

I suggest this issue to @Ktn-mariam and @jatingodnani, happy coding :) 🚀⭐️

**Comment by Ktn-mariam** [comment]
Thank you for bringing this to my attention, @Nayaker. I would like to take up this issue!

**Comment by Nayaker** [comment]
That's great to hear, @Ktn-mariam.
