### ISSUE TITLE
Extract text from PDF in React JS

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#166]
The issue is to extract the text information from a PDF file and store it in a useState. 

<img width="1439" alt="Screenshot 2023-10-18 at 6 45 12 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/49d4bd3d-6c93-411d-81b1-b72f5556cc9b">

You need to update ```<Route path="/resume-questions" element={<ResumeQuestions/>} />```

**Comment by Nayaker** [comment]
Please have a look @thakurthegr8

**Comment by thakurthegr8** [comment]
@Nayaker will look into this if there's a feasible solution as most of ai apis are paid.

**Comment by Nayaker** [comment]
Yes, I am aware that most of the APIs are paid for this. But, I think there are a couple of npm packages like `pdfreader` which does this.

**Comment by jatingodnani** [comment]
Pdf extractor is an option

**Comment by Mohit030802** [comment]
I can solve this is no time.Please assign it to me

**Comment by Mohit030802** [comment]
I can solve this is no time.Please assign it to me

**Comment by Nayaker** [comment]
@thakurthegr8 any update??

**Comment by Nayaker** [comment]
> I can solve this is no time.Please assign it to me

Please wait as the issue is already assigned

**Comment by Nayaker** [comment]
Ok sure @thakurthegr8. 

@Mohit030802 This issue is assigned to you now!

**Comment by Nayaker** [comment]
Completed by @Mohit030802 by his amazing contribution on #173

**Comment by thakurthegr8** [comment]
https://github.com/Nayaker/AlgoListed/assets/68949544/5525eef7-62f3-48c5-abfc-59605b420720

@Nayaker Tried to do some experiments using openai, multer and some prompt engineering.

**Comment by Nayaker** [comment]
Amazing work @thakurthegr8, can we get on a meet to discuss this?

**Comment by thakurthegr8** [comment]
sure @Nayaker

**Comment by thakurthegr8** [comment]
send me a meet link

**Comment by Nayaker** [comment]
Ok

**Comment by Nayaker** [comment]
https://meet.google.com/spu-sfsz-azf
Join this :)
