### ISSUE TITLE
Implement Open AI API to Find Relevent Questions 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#176]
![Minimalist Thank You Card ](https://github.com/Nayaker/AlgoListed/assets/93304796/ed818b62-f9c3-4999-87ec-7ef50129445b)

In the left selector, we will have 5 options as : 
- Google 
- Amazon
- Samsung 
- Top MNCs
- Startups

There would be 5 different files for each of the 5 which will contain the prompt for each, which will be used. 

In the right selector, we will have 3 options as : 
- Beginner
- Intermediate
- Expert

Now use open AI API to display the questions.

**Comment by Nayaker** [comment]
@thakurthegr8, please have a look at this issue.

**Comment by thakurthegr8** [comment]
@Nayaker sure.

**Comment by thakurthegr8** [comment]
@Nayaker please add hacktoberfest labels
