### ISSUE TITLE
Create a Modal for Premium Feature Buttons | CSS + Styled Components | HacktoberFest 2023

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#184]
## Issue :
<img width="1440" alt="Screenshot 2023-10-26 at 6 02 52 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/bfc67708-3476-4501-87b0-346bc69ebd81">

Within the page accessible through the route <Route path="/contests-archive" element={<ContestArchive/>} />, we aspire to introduce an engaging user experience. When a visitor clicks on any of the currently inaccessible options, a captivating modal will gracefully appear. This modal will kindly inform the user that premium features are on the horizon, and to stay informed about their arrival, all that is required is to provide an email address. We aim to make this interaction both visually captivating and user-friendly, ensuring that it becomes an integral part of your journey on our platform. To ignite your inspiration, imagine a design similar to the one showcased below:

![image](https://github.com/Nayaker/AlgoListed/assets/93304796/bc6a3884-f837-405b-9d85-2b838fd1e938)

## How to run the repo locally : 
Check #104 

## Important :
1. Please don't change any file other than what is mentioned - if you want please mention it below. 

## How to get your PR accepted :
1. Consider giving our project a star as it helps enhance the project's credibility.
2. Write the PR title as - #184 Issue Resolved | {something you want to mention}
3. Write a good PR comment with a **screen-shot** of the work
4. Make sure to generate the PR to the main branch of this repository. 

</br>
Express your interest in the open-conversion section below to request this issue as an assignee! Enjoy your coding journey! :) 🚀

**Comment by shadow-ryu** [comment]
@Nayaker  Can I work on this issue?

**Comment by Nayaker** [comment]
Great @shadow-ryu! Thank you for expressing your interest. I'm assigning this issue to you. Much appreciated!
