### ISSUE TITLE
Add an Input Field for OPEN-AI API Key in Resume Question Page 

### ISSUE THREAD

**Issue by Mohit030802** [Nayaker/AlgoListed#185]
Hey folks 🚀

### ISSUE DESCRIPTION

Currently, our resume question page lacks the functionality to incorporate user-specific data from external sources through APIs. To enhance user experience and provide more customized results, we propose the addition of an input field for API key entry on the resume question page. This will allow users to enter their API key, and subsequently, the system can fetch and display relevant results based on their unique data.

![image](https://github.com/Nayaker/AlgoListed/assets/80634689/12f9e806-108b-4e31-8091-22971a6c613e)

### SCOPE

1. **Frontend:** Introduce a new input field on the resume question page to collect the API key.
2. **Backend:** Develop the necessary logic and connections to retrieve data based on the API key.
3. **Security:** Ensure the secure handling and storage of API keys.

### Acceptance Criteria:

- A new input field for entering the API key should be added to the resume question page.
- Upon submission of the API key, the system should validate it.
- If the API key is valid, the system should fetch and display relevant data accordingly.
- Proper error handling should be in place for invalid API keys or failed API requests.
- Ensure that user API keys are securely stored and handled.

### Additional Information:

- To run the repo into your local Enviroment refer #104.
- To work on Backend you need to add your own Api key for development. You can change the Api key in ```backend/Router/ai.js```
- If You find any issue other than this feel free to tag us, We will help 👍.

**Comment by Vipaaah** [comment]
Hi @Mohit030802 , I am new to open source and this is my first issue. I wanted to ask what kind of data do you want to display when the api key is used. 
I am a begginer in coding so I apologise if its a dumb question

**Comment by Mohit030802** [comment]
Hi @Vipaaah, Here we are analyzing the Resume uploaded by the user to fetch personalized questions related to the tech stack mentioned in the resume that will help the user with their interviews. For that, we are using open AI. So, in order to analyze the resume users have to enter their own API key and after that, the user can upload the resume and the results will be fetched.

So we need an input section we user will enter his API key and it will fetched and the results will be shown based on the resume.

Regarding the 404 can explain more about what error you are getting.

**Comment by Mohit030802** [comment]
You are new to open source so this particular issue may be a bit challenging, but don't worry! We'll be posting some beginner-friendly issues soon. Be sure to 'star' this repository for updates.

**Comment by Vipaaah** [comment]
TYSM for replying , I was trying to wrap my head around the issue, but failed to do so . When the frontend loads ,it shows 404 error 'GET /dummy-link1 404 0.330 ms - 150'.

**Comment by Vipaaah** [comment]
Alright thanks, and yeah I've already starred this repo, you guys seem to be highly skilled so looking forward to learn from you guys
