### ISSUE TITLE
Add option to filter out problems that has been "Marked as Completed" and "Mark for Later" in the Coding Sheets

### ISSUE THREAD

**Issue by KAIMonmoy** [Nayaker/AlgoListed#190]
![image](https://github.com/Nayaker/AlgoListed/assets/33915686/ce611564-d14a-4285-ba96-422bdb9f423f)

**Is your feature request related to a problem? Please describe.**
I need the option to figure out which problems I've marked for doing later.

**Describe the solution you'd like**
Just add a filter option to filter "Marked as Completed" and "Mark for Later" problems

**Comment by Nayaker** [comment]
Sure, @KAIMonmoy, we think this feature would be a great addition, and we're planning to implement it in the near future.

_If anyone is interested in contributing to the development of this feature, please feel free to share your implementation ideas, and we'll be happy to assign this issue to you._

**Comment by Nayaker** [comment]
<img width="1439" alt="Screenshot 2023-11-08 at 9 22 01 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/1e6a2080-cc62-457c-b102-24ae0b9a96fd">

**Comment by RajMhatre20** [comment]
In the image you shared, what if someone has marked some problems of medium difficulty for later? They would need to select both options, which, in my opinion, may not be the most effective approach, potentially causing confusion and complicating space management, especially if more features are being added.

I propose implementing a drop-down menu for status and difficulty to enhance the clarity and tidiness of the UI. 
If you find my idea promising, would you kindly consider assigning this issue to me?

**Comment by Nayaker** [comment]
Interesting I like the idea but can you explain the idea a bit more? Like just give an sketch for the UI you are suggesting

**Comment by Nayaker** [comment]
> In the image you shared, what if someone has marked some problems of medium difficulty for later? They would need to select both options, which, in my opinion, may not be the most effective approach, potentially causing confusion and complicating space management, especially if more features are being added.
> 
> I propose implementing a drop-down menu for status and difficulty to enhance the clarity and tidiness of the UI. If you find my idea promising, would you kindly consider assigning this issue to me?

@RajMhatre20 Interesting I like the idea but can you explain the idea a bit more? Like just give a sketch for the UI you are suggesting
