### ISSUE TITLE
Implement Dark Mode for Graphs 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#191]
The website has just introduced a new feature: dark mode. While the entire website now supports dark mode, there is a need to extend this functionality to the graphs as their light mode version doesn't blend well with the dark mode.

**/contests-archive** and **/contest-analysis/weekly-contest-362** are two pages where change is required.

<img width="1439" alt="Screenshot 2023-11-07 at 10 03 04 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/00435575-f731-4671-a41d-4a0966e87a89">

<img width="1439" alt="Screenshot 2023-11-07 at 10 08 23 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/85597bd8-68a0-4ad3-9af5-5062f00d8a4e">

<img width="1439" alt="Screenshot 2023-11-07 at 10 08 32 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/8920cf7f-7af9-42e8-8a6d-0bcb214c7d3f">

**Comment by Nayaker** [comment]
@Ktn-mariam please check this issue 🚀

**Comment by Ktn-mariam** [comment]
I would like to take up this issue @Nayaker, thank you!

**Comment by Nayaker** [comment]
Amazing @Ktn-mariam 🚀, I am assigning the task to you!
