### ISSUE TITLE
Create a stop watch feature in coding sheets page

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#197]
## Feature 
A user should have the capability to monitor the amount of time it takes to solve a question.

<img width="1440" alt="Screenshot 2023-11-10 at 9 07 29 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/cbb576bd-a420-4f4a-abe9-2b2898975ace">

## Implementation 
1. When a person clicks the stopwatch button the timer starts. 
2. The time running is displayed as shown in the figure
3. When the clock is running change the icon to (import AlarmOnIcon from '@material-ui/icons/AlarmOn';) - if the user hits this then the time stops and gets saved in the cache
4. Redo button: Makes the time = 0
5. If time > 1 day then write invalid instead of showing the time.

**Comment by Nayaker** [comment]
@RajMhatre20 interested??

**Comment by RajMhatre20** [comment]
Yes I'll try

**Comment by Nayaker** [comment]
Amazing I am assigning the issue to you then 🚀

**Comment by RajMhatre20** [comment]
Is there any problem with the pr?

**Comment by Nayaker** [comment]
No it works just fine, I re-opened the issue by mistake.
