### ISSUE TITLE
[enchancement] Clean and optimize codingsheets file

### ISSUE THREAD

**Issue by RajMhatre20** [Nayaker/AlgoListed#202]
While developing a feature in CodingSheet.js, I noticed some unwanted functions and a significant amount of commented-out code. Additionally, I observed suboptimal performance in the React developer tools, with the page taking an unusual amount of time to load. I also noticed that many elements are being re-rendered unnecessarily. For example, when marking items as completed or for later use, it seems unnecessary for the header to re-render. Could we investigate and address these issues to optimize performance and code cleanliness?

Furthermore, on the current live website, the coding sheet doesn't seem to load data.

**Comment by Nayaker** [comment]
Hi, appreciate your keen observations and detailed feedback. Thanks for highlighting the API issue; it's in the process of being updated and should be back online within a couple of hours.

I appreciate the issue you've raised, and I'd like to include a few additional points to enhance coding-sheets further : 
    - [ ] The issue you are suggesting 
    - [ ] The topics filter is not working properly - work on the topics filter 
    - [ ] Can we make the clock feature a bit more attractive? (I would like to hear your suggestions)

**Comment by Nayaker** [comment]
Hi, appreciate your keen observations and detailed feedback. Thanks for highlighting the API issue; it's in the process of being updated and should be back online within a couple of hours.

I appreciate the issue you've raised, and I'd like to include a few additional points to enhance coding-sheets further :
- [ ] The issue you are suggesting
- [ ] The topics filter is not working properly - work on the topics filter
- [ ] Can we make the clock feature a bit more attractive? (I would like to hear your suggestions)

**Comment by Nayaker** [comment]
> if you think this is a valid issue, can i work on this?

Absolutely, @RajMhatre20! I appreciate the contributions you've made, and I'd be thrilled to have you work on this issue.

**Comment by Nayaker** [comment]
API is working fine now! @RajMhatre20

**Comment by RajMhatre20** [comment]
Ah, I'm not yet adept at UI, but since you're asking for my suggestion, I would propose hiding the timer that shows 0 seconds for each problem. Instead, display only those problems where the timer is activated. This would reduce the time needed to identify which problems have active timers. This is just a suggestion, and I can't be certain it's a better idea than the existing one.

**Comment by Nayaker** [comment]
Appreciate the recommendation; I'll make a note of it. @RajMhatre20

**Comment by Nayaker** [comment]
@RajMhatre20 were you able to figure out why filters are not working properly??

**Comment by RajMhatre20** [comment]
It seems to be working on my end. Could you provide the steps to recreate the problem?

**Comment by Nayaker** [comment]
Can you please join : https://meet.google.com/trs-zbbz-eoj

**Comment by RajMhatre20** [comment]
Got it
