### ISSUE TITLE
Charts for Resume AI page 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#212]
<img width="1440" alt="Screenshot 2023-11-18 at 8 47 09 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/e27bc05d-e03a-493a-9a88-a68fb53eb9c1">

<img width="550" alt="Screenshot 2023-11-18 at 8 46 38 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/ca5de516-6aad-4bfd-a48d-9ba2762a2ffb">

In the resume-related questions, we aim to showcase charts to the user. Currently, you can utilize dummy useState values for the three specified criteria and generate charts accordingly. Ensure the charts align with the other charts on the website, and make them adaptable for both light and dark modes. Happy coding 🚀

**Comment by Ktn-mariam** [comment]
@Nayaker I will take up this issue, thanks!
