### ISSUE TITLE
User Sign-Out Issue Upon Refresh with Firebase "Continue with Google" Login

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#216]
**Page:** Create Problem Sheet

**Issue:** User Sign-Out Upon Page Refresh

Upon refreshing the site, users are experiencing an unexpected sign-out, despite having initially logged in through the Firebase "Continue with Google" login system.

**Expected Behavior:**
Users should persistently remain logged in even after refreshing the page.

Note:
_The authentication system is connected to the backend. Please review the previous code for context. If you encounter any challenges, feel free to comment below for assistance._

Thank you!

**Comment by Nayaker** [comment]
@IrfanSalim please check this :)

**Comment by IrfanSalim** [comment]
On it @Nayaker :)
