### ISSUE TITLE
Create Filters for All Internship & Job Opportunities Page 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#217]
<img width="1440" alt="Screenshot 2023-11-24 at 1 21 12 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/c5904785-66ad-480a-a03f-c4d754bbd341">

## Issues 
**We need to make the below two features functional :** 
1. The All Internship & Job Opportunities Page displays data from a spreadsheet, listing it for users. However, there's a need for users to efficiently filter the displayed content.
2. To enhance user experience, three buttons have been provided—marking the opening as filled, expressing disinterest in the listing, or indicating interest by liking the listing. These features aim to enable users to actively track and manage their preferences.

_Keep the tracking data in the localhost, you can check other pages like **coding sheets** to get an idea._

## Data format 
We are calling the API : https://script.googleusercontent.com/macros/echo?user_content_key=-uzK50zBD6RPL-G3EofKPmSrK5MvKfFsup3Uhju_sgB_FZv4hE0dYdZ9FDqz6jwMdYtgj8m9UOeQhC2KRwX0uVtqD5cs023wm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnA8Tr49F1Ivtr0o6Yp4fjnD9VY8k1Q0AdNpbEobTJSVU02RPIupYF5H0LqOn1gHHuTQr3i-TjMlDArlJytlu8mpjZbJ2bHHlb9z9Jw9Md8uu&lib=M_adtjhtYqTY4x3CHvLkZEzxNTvjCbw04 

<img width="1440" alt="Screenshot 2023-11-24 at 1 22 39 PM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/a91b1f89-dbe8-4374-9386-0dd7fd60ef13">

**Comment by patilanuja** [comment]
Hello @Nayaker , Can I work on this?

**Comment by Nayaker** [comment]
Great @patilanuja! Thank you for expressing your interest. I'm assigning this issue to you. Much appreciated!

**Comment by Nayaker** [comment]
Any updates, @patilanuja? If you have any questions or would like to discuss anything, feel free to ask. Thank you!

**Comment by khamkarsuraj** [comment]
Hello @Nayaker,
I can work on this issue. Could you please assign this to me?

**Comment by Nayaker** [comment]
> @Nayaker Sorry, I got stuck in another work. For now, I will unassign myself from this issue.

No problem at all, @patilanuja! Thanks for letting me know.

**Comment by Nayaker** [comment]
> Hello @Nayaker, I can work on this issue. Could you please assign this to me?

Hi @khamkarsuraj, Thank you for your interest in contributing! I appreciate your willingness to take on this issue. I've assigned it to you, and feel free to reach out if you have any questions or need further information. Happy coding!
