### ISSUE TITLE
Create Filters for Core Subjects Tracker Page

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#219]
<img width="1440" alt="Screenshot 2023-11-25 at 4 35 43 AM" src="https://github.com/Nayaker/AlgoListed/assets/93304796/583629c6-e321-45bc-9049-9869c7139cb5">

## Issue 
By default, we will have the **All Questions** option as selected. And out of the three options we can select any one option.

**Comment by sabbellasri** [comment]
Hi  Nayaker, I am interested in this issue. could u please assign this to me?

**Comment by Nayaker** [comment]
Great @sabbellasri! Thank you for expressing your interest. I'm assigning this issue to you. Much appreciated!

**Comment by Kunal-debug-png** [comment]
Hi @sabbellasri are you still working on this one?

**Comment by sabbellasri** [comment]
Yes Nayaker, I have started working on this issue.
