### ISSUE TITLE
User Login/SignUp

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#26]
Basic login signup, with rest API and session storage.

**Comment by Nayaker** [comment]
### Basic backend and UI completed. 
<br/>
<img width="338" alt="Screenshot 2022-11-26 at 2 54 26 AM" src="https://user-images.githubusercontent.com/93304796/204056690-73af777f-0e29-4d3d-840c-43607db5cc96.png">

### Next Tasks : 
- Connect MongoDB database
- Signup and Login with email
- User data to be stored globally

**Comment by Nayaker** [comment]
Auth middleware for security needs to be added

**Comment by Nayaker** [comment]
Session Storage

**Comment by akunumanarif** [comment]
Hi @Nayaker 
can you assign me on this ?

**Comment by Nayaker** [comment]
@akunumanarif thank you for your request but actually, we are unfortunately not entertaining this feature as of now.

**Comment by akunumanarif** [comment]
Ok, thank you
