### ISSUE TITLE
Add sorting feature on the coding competitions page

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#42]
When you click on that sort button a drop-down will occur with some specific types of sortings. Please read about the whole task here in this google doc : https://docs.google.com/document/d/1zO3lE-YQSInsA9sFoFC8O7ImOHdjVceL2pqHPnYat-8/edit?usp=sharing 

<img width="576" alt="Screenshot 2022-12-06 at 2 58 53 AM" src="https://user-images.githubusercontent.com/93304796/205746305-d60eddd4-84d9-4893-9e63-526400865dc3.png">

**Comment by ThorezNS** [comment]
Please assign me
