### ISSUE TITLE
Coding Competitions Page - International Timings

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#67]
Write now the API which is fetching the data has the content in Indian time. And when it is being called by the user we are comparing it with the local time of that country. 

The task is to show the data/time respective to the user's country taking the Indian time as standard (Since API is giving the data in Indian time).

Or you can suggest me, to convert the API timings to International time if it is easier for you to convert.

**Comment by dineshigdd** [comment]
So, you mean in the table at https://algolisted.com/coding-competitions , you use the Indian time. But, do you want to display it local time of a particular country?

**Comment by Nayaker** [comment]
_You can convert IST(India time) to UTC, and UTC to the local time of the region._ - exactly this is the task. I am assigning this to you, happy coding :)

**Comment by dineshigdd** [comment]
ok..thank you. I will work on it.

**Comment by dineshigdd** [comment]
I want to give an update on thisit. I am still working on it. I have completed some work. As soon as I tested and competed it , I will make a PR

**Comment by dineshigdd** [comment]
I sent the PR with a description

**Comment by Nayaker** [comment]
Yep, reviewed it :) #73
