### ISSUE TITLE
Separation based on main tag - Coding Sheets page

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#71]
There is an exciting task that may require some thought to complete. 

If you visit the https://algolisted.com/coding-sheets/two-pointers-lc page, you will see that we have tags on each question. One of these tags is the main tag - (they have a slightly darker border). The task is that we want all the questions to be listed under this main tag.

![image](https://user-images.githubusercontent.com/93304796/210525922-2f6570a3-a4d9-42ee-b74d-077986465495.png)

In the above, example `2 Sum problem similar` and `Tapping rain water similar` are the two main tags.

The main tag can be something like "Day 1", "Day 2" or "2 Sum problem similar," as seen above, etc.

Here is a picture that may provide further insight.

![image](https://user-images.githubusercontent.com/93304796/210526424-2290998b-b761-4315-8c77-8599da2a9e7a.png)

**Comment by Nayaker** [comment]
@JordanAdair

**Comment by JordanAdair** [comment]
Feel free to assign me to this. 

Do you want it to collapse similar to the example you provided in #61?

**Comment by Nayaker** [comment]
The main image we need to build is similar to the one I provided before and above as well. Here it is again:

<img src="https://user-images.githubusercontent.com/93304796/210534400-7e0f4e75-2018-4064-ad1f-0dc6d94a1711.png" width="400px"/>

**Comment by JordanAdair** [comment]
Got it. I'll start working on this shortly.

**Comment by Nayaker** [comment]
I wanted to let you know that I will be taking a break from work and social media for a few days. I just wanted to inform you, @JordanAdair :)

**Comment by JordanAdair** [comment]
No problem at all! Thanks for letting me know. 
Enjoy your time off. 😄

**Comment by Nayaker** [comment]
@JordanAdair I am back :) Any updates on the task ?

**Comment by JordanAdair** [comment]
Welcome back, @Nayaker. 
I've also decided to take a little break, myself. I'll be back in a bit.

**Comment by Nayaker** [comment]
Oh, that's really great! Have fun :)
