### ISSUE TITLE
Simple SEO 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#75]
I am trying to get my website listed on Google and to appear in search results when the exact website name is searched. I have already added the necessary Google scripts and meta tags, but the site has not shown up in search results after 10 days. I am unsure of what else may be causing this issue.

Everything relevant is on the <a href="https://github.com/Nayaker/AlgoListed/blob/main/client/public/index.html" target="_blank">index.html file</a>

**Comment by Nayaker** [comment]
Hey @dineshigdd, I think you would be great at tackling this problem! You already have a website with strong search engine optimization skills, so I think you'd be able to handle it with ease.

**Comment by dineshigdd** [comment]
I am sorry for the late reply. I do have some basic knowledge of SEO. However, For the most part,  SEO for my blog, I used SEO plugins. Anyway , this issue seems completed

**Comment by Nayaker** [comment]
No problem, appreciate the update.
