### ISSUE TITLE
Fix colors in Chart JS

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#79]
<img width="639" alt="Screenshot 2023-01-12 at 12 15 50 PM" src="https://user-images.githubusercontent.com/93304796/211996709-19d48220-0209-44b0-9096-8812d35e791b.png">

The goal is to ensure the colors in the donut chart are cohesive and consistent, rather than appearing vastly different from adjacent sections.

https://algolisted.com/coding-sheets/striver-sde-sheet

**Comment by lokeshvasnik** [comment]
Let me give a try

**Comment by Nayaker** [comment]
Sure, I will assign this issue to you.

**Comment by lokeshvasnik** [comment]
Great

**Comment by lokeshvasnik** [comment]
![Screenshot from 2023-01-12 12-39-13](https://user-images.githubusercontent.com/91425128/212000623-745f1c30-2024-477e-b4c6-a26c69fbbe0a.png)

**Comment by Nayaker** [comment]
It is a bit hard to understand the issue like this, please try to play around with it a bit more. I believe you will be able to solve the error. 

Try `--force` while installing.
