### ISSUE TITLE
Dark Mode Feature

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#80]
- Make an icon on the top right for toggling the dark mode. 

<img width="896" alt="Screenshot 2023-01-23 at 3 44 18 AM" src="https://user-images.githubusercontent.com/93304796/213943144-6eec23c8-0f9c-431e-9e46-9d79489d2f62.png">

- The colors in the dark mode should be _non-reflection colors_ basically a bit lighter black in the background. Below is a sample image for reference of colors.

  <img width="966" alt="Screenshot 2023-01-12 at 12 35 32 PM" src="https://user-images.githubusercontent.com/93304796/211999939-97a9b412-97ce-40a8-b2f3-d169d87301bd.png">

**Comment by apala7778** [comment]
hey i would like to work on this. Can i get started ? I have had worked with enabling Dark Mode. please assign me this

**Comment by Nayaker** [comment]
Sure. Review the codes and feel free to ask any questions you may have here.

**Comment by Nayaker** [comment]
@apala7778 Any updates on this ?

**Comment by deepaksuthar40128** [comment]
Hey i want to work on this

**Comment by Nayaker** [comment]
Sure, I am assigning this issue to you @deepaksuthar40128

**Comment by nesyG** [comment]
Hello @Nayaker, if no one is working actively on the issue I can start right away, can you assign me?

**Comment by Nayaker** [comment]
Certainly, please proceed. The CSS code is quite rough and requires some cleaning up, which made some individuals apprehensive about tackling this assignment. I was planning on addressing this later, but if you can perform this task accurately, that's great.

**Comment by Nayaker** [comment]
@nesyG any update?

**Comment by saurabh-sen** [comment]
Hey, I wanna work on this, 
but dont know much about github contributions.

can tell me what are you using for styling? like css, tailwind css, scss, mui what?

**Comment by NawinKumarSharma** [comment]
Hello @Nayaker,  can you assign this to me?

**Comment by Nayaker** [comment]
Sure, I would suggest to start with the coding sheets page first https://algolisted.com/coding-sheets/striver-sde-sheet

**Comment by Ankitmohanty2** [comment]
hey can i work on this issue i want to contribute through hacktoberfest 2023.

**Comment by Nayaker** [comment]
Sure @Ankitmohanty2  you can share this issue with @NawinKumarSharma. 
Nawin is already working in dark mode for <a href="https://algolisted.com/coding-sheets/striver-sde-sheet">Coding Sheets Page</a> you can start working on the dark mode for <a href="https://algolisted.com/resources">Resources Page</a>. 

Also, it would be better if @Ankitmohanty2 and @NawinKumarSharma, you both communicate with each other to get better results. _All the PRs will be accepted which are relevant._

**Comment by Ankitmohanty2** [comment]
@NawinKumarSharma can I add dark mode in resources page I wanna contribute too.

**Comment by mohitsaini07** [comment]
Hi Nayaker, I would like to work on this issue. if available!

**Comment by Nayaker** [comment]
Yeah sure it is up! @Ankitmohanty2 and @mohitsaini07 you all can start working on different pages of your choice!

**Comment by soumyadeeproychowdhury** [comment]
Hi! Could you assign me this would love working on it!

**Comment by thakurthegr8** [comment]
is this issue still available? @Nayaker

**Comment by Nayaker** [comment]
@thakurthegr8, we appreciate your interest, but we regret to inform you that the dark mode features are being discontinued.
