### ISSUE TITLE
Enter proper links in Landing Page Footer

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#87]
Currently, the links are unfunctional, find the correct links and enter them. 

If you face difficulty in finding any link, you can ask it here.

**Comment by dineshigdd** [comment]
Ok, I will do this.  Would you please assign me to this?

**Comment by Nayaker** [comment]
Sure @dineshigdd ✨.

**Comment by dineshigdd** [comment]
I am working on it. I will ask if I could not find any screens associated with a particular link

**Comment by Nayaker** [comment]
Yeah sure.

**Comment by Nayaker** [comment]
@dineshigdd You can also change the footer content, as most of them are irrelevant currently.

**Comment by dineshigdd** [comment]
Ok

**Comment by dineshigdd** [comment]
yes ....while I was working on it, I found that most components were missing. I linked About team, login and created an account. Do you want me to create demo pages for missing links?
or, what are the irrelevant items? Maybe, you can remove one item from the General column . for example "Trust and security". You may include that as a section in "Terms and Conditions". 
Other two columns seems ok to me as these are common for many websites / web apps

**Comment by Nayaker** [comment]
Actually, I will have to make the general column for open-source contributors and some other stuff. You may consider on adding links to other sections rather than the general column.

**Comment by dineshigdd** [comment]
Ok
