### ISSUE TITLE
Update Graph UIs using Chart JS in React 

### ISSUE THREAD

**Issue by Nayaker** [Nayaker/AlgoListed#97]
I would like to enhance the user interface for the LeetCode contest analysis feature in the project. The technical aspects of data retrieval and display are already functional; however, the current user interface does not meet the desired standards. Our primary objective is to align the UI with the design provided in the Figma link below:

**<a href="https://www.figma.com/file/oD1lNnn7G0AotvGc3j5EIL/Algolisted?type=design&node-id=0-1&mode=design&t=Kg0ZIlT2hIzXz6pK-0" target="_blank">Click here to go to Figma Page</a>**

The primary focus will be on improving the appearance and functionality of the charts in the user interface. Other UI enhancements may be addressed in separate issues to streamline the development process. Your feedback and collaboration on achieving the desired UI improvements are highly appreciated.

<hr></hr>

Here are some key points to address : 
1. The primary file that requires modifications is located in the path client > Screen > ContestAnalysis.js.
2. The line chart component is situated in client > Components > LineChart.js.
3. You have the flexibility to customize the colors in the user interface as per your preference; it's not mandatory to strictly adhere to the Figma color scheme. Just try to keep the structure the same as Figma.

Notification to: @YakovlevCoded @mika-alaoutinen @Yeranosyan @coditech0926 @Njengah @redonwhite @Ktn-mariam @surajthecreator003  @jhonnold @Arantiryo @julianna-ciq @BK2004 @deborasous @SSYernar @oprstchn @bhogan-mitre @dmt0

**Comment by coditech0926** [comment]
Hello,
I checked your figma.
Please contact me

**Comment by Nayaker** [comment]
How can I get in touch with you? Could you kindly share your email address or another contact method?

**Comment by coditech0926** [comment]
skype -> live:.cid.f458d28ee41437fd
gmail -> coditech.super926@gmail.com

**Comment by Ktn-mariam** [comment]
Hello, I am interested in contributing too. You can contact me at my email: mariamkhatoon996@gmail.com
Thank you.

**Comment by Yeranosyan** [comment]
Looks nice template in Figma , whit chart.js)


Sent from Yahoo Mail for iPhone


On Monday, October 2, 2023, 7:57 AM, Atanu Nayak ***@***.***> wrote:




Closed #97 as completed via #105.
